version: "2"
services:
    www:
        build: php/.
        ports: 
            - "80:80"
        volumes:
            - 'C:\Users\ingjr\Proyectos\php\laravelgenda\src:/var/www/html/'
        links:
            - db
        networks:
            - default
    db:
        image: mysql
        ports: 
            - "3308:3306"
        environment:
            MYSQL_DATABASE: laraveldb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - persistent:/var/lib/mysql
        networks:
            - default
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8004:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
volumes:
    persistent: